// Copyright 2019. DW </> Web-Engineering. All rights reserved.
// PLEASE DO NOT EDIT THIS FILE! PLEASE DO NOT EDIT THIS FILE!  PLEASE DO NOT EDIT THIS FILE!  PLEASE DO NOT EDIT THIS FILE!

import React from 'react'
import ReactDOM from 'react-dom';
import Routes from "./routes";
import {BrowserRouter} from "react-router-dom";

const initProps = window.INIT_PROPS;
const renderDOM = initProps.domId;

const App = ({ ...props }) => (
    <BrowserRouter basename={`${(props.baseUrl).replace(/&amp;/g, '&')}`}>
        <Routes {...props} />
    </BrowserRouter>
);

ReactDOM.render(<App {...initProps} />, document.getElementById(renderDOM));

// Copyright 2019. DW </> Web-Engineering. All rights reserved.
// PLEASE DO NOT EDIT THIS FILE! PLEASE DO NOT EDIT THIS FILE!  PLEASE DO NOT EDIT THIS FILE!  PLEASE DO NOT EDIT THIS FILE!
