/*
 * MIT License
 *
 * Copyright (c) 2020 DW Web-Engineering
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import React, {Suspense} from 'react'
import ReactDOM from 'react-dom';
import Routes from "./routes";
import {HashRouter} from "react-router-dom";
import '../../I18n'
import ErrorBoundary from "../../ErrorBoundary";
import "../../Circle.scss"

const initProps = window.INIT_PROPS;
const renderDOM = initProps.reactDOM;

const App = ({...props}) => (
    <ErrorBoundary>
        <Suspense fallback={(
            <div className="sk-circle">
                <div className="sk-circle1 sk-child"/>
                <div className="sk-circle2 sk-child"/>
                <div className="sk-circle3 sk-child"/>
                <div className="sk-circle4 sk-child"/>
                <div className="sk-circle5 sk-child"/>
                <div className="sk-circle6 sk-child"/>
                <div className="sk-circle7 sk-child"/>
                <div className="sk-circle8 sk-child"/>
                <div className="sk-circle9 sk-child"/>
                <div className="sk-circle10 sk-child"/>
                <div className="sk-circle11 sk-child"/>
                <div className="sk-circle12 sk-child"/>
            </div>
        )}>
            <HashRouter>
                <Routes {...props} />
            </HashRouter>
        </Suspense>
    </ErrorBoundary>
);

ReactDOM.render(<App {...initProps} />, document.getElementById(renderDOM));

// Copyright 2019. DW </> Web-Engineering. All rights reserved.
// PLEASE DO NOT EDIT THIS FILE! PLEASE DO NOT EDIT THIS FILE!  PLEASE DO NOT EDIT THIS FILE!  PLEASE DO NOT EDIT THIS FILE!
